### ISSUE TITLE
Update https://github.com/googleapis/gapic-generator-java/blob/main/DEVELOPMENT.md

### ISSUE THREAD

**Issue by alicejli** [googleapis/sdk-platform-java#1131]
[https://github.com/googleapis/gapic-generator-java/blob/main/DEVELOPMENT.md is ](https://github.com/googleapis/gapic-generator-java/blob/main/DEVELOPMENT.md#running-the-plugin) instructions are out of date and confusing.

Update with correct instructions on how to run and test a local copy of the microgenerator.

**Comment by blakeli0** [comment]
What exactly is out of date? We could organize it better but I think all of the commands are still update to date. Are you referring to the newly added multi module changes?

**Comment by alicejli** [comment]
Yes; given the multi module changes I think some of the instructions need to be updated. Especially if we should no longer be using bazel to invoke any of the tests we should remove those instructions.

**Comment by alicejli** [comment]
This has been updated.
