### ISSUE TITLE
Generator incorrectly sets the composeTransport sample's region tag

### ISSUE THREAD

**Issue by lqiu96** [googleapis/sdk-platform-java#1272]
Context:
The SyncCreateSetCredentialsProvider sample already exists: https://github.com/googleapis/google-cloud-java/blob/56c9a8a29c1d04baed958cc028918eea5995aa17/java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider.java

and it properly showcases setting the credentials. The SyncCreateSetCredentialsProvider1 sample should be named something that reflects that it is using httpjson.

This generator's logic seems to set the wrong region tag name: 
https://github.com/googleapis/gapic-generator-java/blob/8ef747b244c9bed128252cb6913d954ae7270251/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/samplecode/ServiceClientHeaderSampleComposer.java#L345

The logic may have been mistakenly copied over. This is creating samples with `SyncCreateSetCredentialsProvider1` as the filename instead of something like `ComposeTranport` or `UseHttpJsonTransport`.

https://github.com/googleapis/google-cloud-java/blob/56c9a8a29c1d04baed958cc028918eea5995aa17/java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider1.java#L23

**Comment by suztomo** [comment]
@lqiu96 Is the screenshot below capturing the incorrectness you found?

![image](https://user-images.githubusercontent.com/28604/230109175-02c152ef-053e-4677-8a1c-4ea7dbc17acc.png)

**Comment by lqiu96** [comment]
I'll update the title to reflect the entire scope.

The screenshot shows the region tag issue. The `SyncCreateSetCredentialsProvider` sample already exists: https://github.com/googleapis/google-cloud-java/blob/56c9a8a29c1d04baed958cc028918eea5995aa17/java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider.java

and it properly tests setting the credentials.

The `SyncCreateSetCredentialsProvider1` sample should be about the sample showcasing using httpjson. The other issue is that the file name/ class is set incorrectly. Perhaps something like `tpu_v2_generated_Tpu_Create_HttpJson` or something.

**Comment by suztomo** [comment]
As of today, the generated sample still has the name `SyncCreateSetCredentialsProvider1`:

```
suztomo@suztomo2:~/google-cloud-java$ grep -ir SyncCreateSetCredentialsProvider java-tpu
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2alpha1/tpu/create/SyncCreateSetCredentialsProvider.java:public class SyncCreateSetCredentialsProvider {
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2alpha1/tpu/create/SyncCreateSetCredentialsProvider.java:    syncCreateSetCredentialsProvider();
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2alpha1/tpu/create/SyncCreateSetCredentialsProvider.java:  public static void syncCreateSetCredentialsProvider() throws Exception {
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v1/tpu/create/SyncCreateSetCredentialsProvider.java:public class SyncCreateSetCredentialsProvider {
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v1/tpu/create/SyncCreateSetCredentialsProvider.java:    syncCreateSetCredentialsProvider();
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v1/tpu/create/SyncCreateSetCredentialsProvider.java:  public static void syncCreateSetCredentialsProvider() throws Exception {
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider.java:public class SyncCreateSetCredentialsProvider {
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider.java:    syncCreateSetCredentialsProvider();
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider.java:  public static void syncCreateSetCredentialsProvider() throws Exception {
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider1.java:public class SyncCreateSetCredentialsProvider1 {
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider1.java:    syncCreateSetCredentialsProvider1();
java-tpu/samples/snippets/generated/com/google/cloud/tpu/v2/tpu/create/SyncCreateSetCredentialsProvider1.java:  public static void syncCreateSetCredentialsProvider1() throws Exception {
```
