### ISSUE TITLE
Consider moving ProtobufMessageFeature native image configuration to gax

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/sdk-platform-java#1323]
Currently java-compute brings in gax-grpc for the purpose of bringing in ProtobufMessageFeature. The `ProtobufMessageFeature` class is used to register reflection configurations for all the sub-classes of [`com.google.protobuf.GeneratedMessageV3`](https://github.com/protocolbuffers/protobuf/blob/main/java/core/src/main/java/com/google/protobuf/GeneratedMessageV3.java) which is used by generated client libraries. 

However, adding a dependency on gax-grpc can cause confusion especially when a library (such a java-compute) is REST-based and has also resulted in some unintended behavior (https://github.com/googleapis/java-compute/pull/721) during native image compilation. 

TODO:
The dependency on gax-grpc needs to be removed from java-compute once this change is made, released and gax is upgraded in the libraries

cc: @blakeli0 @suztomo

**Comment by mpeddada1** [comment]
Obsolete as of https://github.com/googleapis/sdk-platform-java/pull/1892. Static reflect-config.json are now generated for all GAPICs

**Comment by blakeli0** [comment]
Thanks @mpeddada1! To follow up, I created https://github.com/googleapis/google-cloud-java/pull/9864 to remove gax-grpc from Compute, PTAL.
