### ISSUE TITLE
Add configuration validation for renovate.json

### ISSUE THREAD

**Issue by emmileaf** [googleapis/sdk-platform-java#1354]
Look into a way to add check to verify `renovate.json` in presubmit, so things like #1349's missed comma can be caught ahead of renovate bot [issue](https://github.com/googleapis/gapic-generator-java/issues/1352).

- I had missed verifying with these steps when making the PR changes: https://github.com/renovatebot/renovate/blob/main/docs/usage/getting-started/installing-onboarding.md#reconfigure-via-pr

- The `renovate-config-validator` can probably be added as a step in an existing presubmit action, or as a pre-commit hook: https://github.com/renovatebot/pre-commit-hooks

**Comment by emmileaf** [comment]
Bleh this totally fell off my radar last year, sorry 🥲 Thank you @ddixit14 for figuring it out! 🙏

**Comment by diegomarquezp** [comment]
cc: @burkedavison @lqiu96 
I'm planning to do a basic parsable JSON test and the use https://docs.renovatebot.com/config-validation/#config-validation

**Comment by diegomarquezp** [comment]
This was already fixed by https://github.com/googleapis/sdk-platform-java/pull/2404
