### ISSUE TITLE
PathTemplate.toString() not reducing wildcards

### ISSUE THREAD

**Issue by jedvardsson** [googleapis/sdk-platform-java#1546]
`PathTemplate.toString()` does not pretty print the template pattern correctly. It does not reduce wildcard bindings `{name=*}` to `{name}` as mentioned in the code.

#### Environment details

OS type and version: MacOS
Java version: Java 19
api-common-java version(s): 2.6.3

#### Steps to reproduce

```java
Assertions.assertEquals("libraries/{library}/books/{book}", PathTemplate.create("libraries/{library}/books/{book}").toString());
```

####  Stack trace
```
org.opentest4j.AssertionFailedError: 
Expected :libraries/{library}/books/{book}
Actual   :libraries/{library=*}/books/{book=*}
```

I believe the problem is in `PathTemplate.peek()`. It looks like the `success` flag is incorrectly initialized to `false`.

https://github.com/googleapis/gapic-generator-java/blob/17d133bd625a9fe203019514aedf63e9fdad97f8/api-common-java/src/main/java/com/google/api/pathtemplate/PathTemplate.java#L1120-L1134

**Comment by emmileaf** [comment]
Attempt to make this patch in #1557 uncovered some downstream logic in the generator that depends on the current behavior of an unreduced `{name=*}`, and possible downstream impact in the generated code - further assessment will be needed before merging the PR.  

@jedvardsson For a bit more context on this issue - is your use scenario is blocked in a specific way on the existing `PathTemplate.ToString()` behavior, and are there any workarounds under the assumption that `{name=*}` will not get reduced?

**Comment by jedvardsson** [comment]
@emmileaf Sorry, for late reply. I must have missed the notification. No, I worked around it by replacing the expression with a wildcard.
