### ISSUE TITLE
Transient workflow failures from javax.net.ssl.SSLHandshakeException: PKIX path validation failed

### ISSUE THREAD

**Issue by emmileaf** [googleapis/sdk-platform-java#1558]
Started noticing CI failures from https://github.com/googleapis/gapic-generator-java/pull/1557 presubmits that do not look related to the changes made. Opening this issue to track and investigate.

Failing workflow run: https://github.com/googleapis/gapic-generator-java/actions/runs/4515219935/attempts/2
Latest successful workflow run: https://github.com/googleapis/gapic-generator-java/actions/runs/4514393539

```
[INFO] --- download-maven-plugin:1.6.8:wget (download-metadata-proto) @ gapic-generator-java ---
Warning:  Could not get content
javax.net.ssl.SSLHandshakeException: PKIX path validation failed: java.security.cert.CertPathValidatorException: validity check failed
    at sun.security.ssl.Alert.createSSLException (Alert.java:131)
    at sun.security.ssl.TransportContext.fatal (TransportContext.java:353)
...
Error:  Failed to execute goal com.googlecode.maven-download-plugin:download-maven-plugin:1.6.8:wget (download-metadata-proto) on project gapic-generator-java: IO Error: Could not get content -> [Help 1]
```

**Comment by emmileaf** [comment]
Looks like this might have been a transient error - keeping this issue open to track for a bit, we can close if it doesn't continue to show up.

**Comment by suztomo** [comment]
@emmileaf One of the step prints Maven version via "-V" option. Are they different between success and failure?

![image](https://user-images.githubusercontent.com/28604/227654107-4d501905-2558-464e-966f-f503915fac47.jpeg)

**Comment by emmileaf** [comment]
Oh, I completely missed this - thank you for the pointer @suztomo! No, there is no difference in the maven versions.

From the previously failed run:
```
> Run mvn -V -B -ntp clean install -DskipTests
Apache Maven 3.[8](https://github.com/googleapis/gapic-generator-java/actions/runs/4515219935/jobs/7952334215#step:4:9).8 (4c87b05d[9](https://github.com/googleapis/gapic-generator-java/actions/runs/4515219935/jobs/7952334215#step:4:10)aedce574290d1acc98575ed5eb6cd39)
Maven home: /usr/share/apache-maven-3.8.8
Java version: 11.0.18, vendor: Eclipse Adoptium, runtime: /usr/lib/jvm/temurin-11-jdk-amd64
Default locale: en, platform encoding: UTF-8
OS name: "linux", version: "5.15.0-[10](https://github.com/googleapis/gapic-generator-java/actions/runs/4515219935/jobs/7952334215#step:4:11)34-azure", arch: "amd64", family: "unix"
```

**Comment by suztomo** [comment]
Thank you for checking. It's a nice mystery.

- By Monday other people may face similar errors if it's widespread problem. Google the error message.
- Create a minimum reproducible job
- See whether you can get the error message in local computer. Diego recently found a nice tool to run GitHub Actions.

**Comment by emmileaf** [comment]
Closing since this transient issue was resolved and no longer reproducible.
