### ISSUE TITLE
Migrate Junit 4 to Junit 5: gax-java

### ISSUE THREAD

**Issue by blakeli0** [googleapis/sdk-platform-java#1611]
Junit 5 provides a lot of [new features](https://www.netcentric.biz/insights/2020/07/junit5-new-features)(namely `Precise exception handling`, `RepeatedTest` etc.) that could be useful to us, it requires Java 8 to be the minimum runtime version, now that Java 8 is the minimum supported version for GAPIC, we can follow the [migration guide](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4) to modernize our testing infra.
We can start with all the handwritten code in this repo, and expand to `google-cloud-java` and eventually handwritten libraries.

**Comment by lqiu96** [comment]
One additional benefit of JUnit 5 from this implementation: https://github.com/googleapis/sdk-platform-java/pull/2485

JUnit 4 doesn't have support for setting Environmental Variables inside tests. JUnit 5 has an extension pack which allows setting and clearing the env vars: https://junit-pioneer.org/docs/environment-variables/
