### ISSUE TITLE
July 31 Release Cycle: Remove PrototypeMessageFeature

### ISSUE THREAD

**Issue by burkedavison** [googleapis/sdk-platform-java#1844]
CC @JoeWang1127 and @blakeli0 : Release managers for the July 31 release train

PR #1841 introduces reflect-config.json generation.

Once this feature has been released and client libraries have been regenerated with the updated gapic-generator-java, remove the `PrototypeMessageFeature` and `-H:-RunReachablityHandlersConcurrently` arguments from [gax-grpc's native-image.properties](https://github.com/googleapis/sdk-platform-java/blob/main/gax-java/gax-grpc/src/main/resources/META-INF/native-image/com.google.api/gax-grpc/native-image.properties#L14-L16).

See also https://github.com/googleapis/sdk-platform-java/pull/1841#discussion_r1262700502

Ensure that we perform downstream testing on client libraries before release to minimize the chance of downstream build failures.

**Comment by zhumin8** [comment]
Done in #1892
