### ISSUE TITLE
Move downstream-compatibility to its own workflow yaml

### ISSUE THREAD

**Issue by blakeli0** [googleapis/sdk-platform-java#1942]
Downstream compatibility checks are not required and could be flaky, our [internal dashboard](https://g3doc.corp.google.com/company/teams/cloud-java/internal/g3doc/CI-Dashboard.md?cl=head) refers to the status of ci.yaml which could be misleading. e.g. [The Bigtable check](https://github.com/googleapis/sdk-platform-java/actions/runs/5919810910/job/16050450507) failed due to network issues.
Consider moving [downstream-compatibility](https://github.com/googleapis/sdk-platform-java/blob/main/.github/workflows/ci.yaml#L289C12-L323) to its own workflow yaml.

**Comment by suztomo** [comment]
That Bigtable check failure seems a valid problem to address. I filed: https://github.com/googleapis/sdk-platform-java/issues/2017

**Comment by blakeli0** [comment]
Thanks for picking this up @suztomo! Do you mind adding the downstream check to our [dashboard](https://g3doc.corp.google.com/company/teams/cloud-java/internal/g3doc/CI-Dashboard.md?cl=head) as a separate column? Or whatever way you want to visualize it.

**Comment by suztomo** [comment]
Sure. Editing the dashboard...
