### ISSUE TITLE
gax: cannot compile with references to SNAPSHOT of `api-common`

### ISSUE THREAD

**Issue by diegomarquezp** [googleapis/sdk-platform-java#1980]
Local development of gax may fail if we are working with a SNAPSHOT of `api-common` (i.e. `bazel build //gax:...`. Maven installs work properly

This is because of [dependencies.properties](https://github.com/googleapis/sdk-platform-java/blob/336e8f36a90a55a50d2da0a7f5ad3d9bb3a87187/gax-java/dependencies.properties#L72) of gax pointing to an old released version. 
If we change this version locally to our working snapshot, the bazel job will fail to find the snapshot because it only fetches from public servers.

This may cause problems with dependencies other than `api-common`

#### edit: adding info from a [personal investigation](https://docs.google.com/document/d/1EOQENZ6fJFjH8pG6-_ls6TlM8Zohhr-lOISfp-5y2KU/edit#heading=h.68zet22hcnf7) (it references the outdated showcase bazel workflow)

Versions declared in the dependencies properties need to be available in the [specified repositories](https://github.com/googleapis/sdk-platform-java/blob/ffc058a08c523b3811b021ec1bc30201452a36c9/gax-java/repositories.bzl#L41). Inspecting the [source](https://github.com/bazelbuild/bazel/blob/3faab8cd03b2de8086a8f4762c8562465fa40866/tools/build_defs/repo/jvm.bzl#L257) of jvm_maven_import_external shows it doesn’t fall back to local servers as the maven command would do. It rather converts artifact coordinates into jar urls to be [downloaded](https://github.com/bazelbuild/bazel/blob/3faab8cd03b2de8086a8f4762c8562465fa40866/tools/build_defs/repo/jvm.bzl#L115) from the specified servers

### Try to remove api-common from Bazel files, e.g. in [java_gapic.bzl](https://github.com/googleapis/sdk-platform-java/blob/ffc058a08c523b3811b021ec1bc30201452a36c9/rules_java_gapic/java_gapic.bzl#L294)
Since gapic-generator-java is now released as a jar with its own dependencies, it may be redundant to manually list dependencies such as common-protos or api-common

### Use maven_install ([example](https://github.com/googleapis/sdk-platform-java/blob/f05f2efe2a33ff88b0c77fafda5d3b7db5b00220/WORKSPACE#L131-L138)) with previous snapshot installed
[This rule](https://github.com/bazelbuild/rules_jvm_external#usage) takes advantage of the availability of local repositories as an option. We would have to run mvn install on the whole repository to have local snapshots available. This doesn’t solve the problem of having a dependencies file in sync with the actual contents of the poms across the repo.
If we have to go with this approach, use release-please to manage the version of api-common.

**Comment by diegomarquezp** [comment]
cc: @blakeli0 @JoeWang1127 @suztomo 
We may want to leave this as an item for the hermetic build

**Comment by suztomo** [comment]
> We may want to leave this as an item for the hermetic build

Sounds good to me.

> it only fetches from public servers

What is "it"? Can you add an URL of the document that states so?

**Comment by diegomarquezp** [comment]
@suztomo I expanded the issue description with some findings of mine, plus I clarified what exactly fails to fetch the SNAPSHOT (the bazel resolution of dependencies)

**Comment by suztomo** [comment]
Thank you. jvm_maven_import_external is old one. maven_install is better.

**Comment by blakeli0** [comment]
This is a valid issue but it is a niche use case. When developing locally, we can use Maven instead. For self-service client, they should always use a released version. Closing as not planned.
