### ISSUE TITLE
`google/cloud/location/locations.proto` should not be added to the proto files when generating from `google/privacy/dlp/v2`

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/sdk-platform-java#1999]
Compare the generating [result](https://paste.googleplex.com/5384226038874112) between `bazel build` and `generate_library.sh`, `google/cloud/location/locations.proto` should not be generated even though `name: '*google.cloud.location.Locations'*` is found in [dlp_v2.yaml](https://github.com/googleapis/googleapis/blob/master/google/privacy/dlp/v2/dlp_v2.yaml).

The protoc command in `bazel build` is (omit unrelevent contents):
```
protoc --experimental_allow_proto3_optional --plugin=protoc-gen-java_gapic=protoc-gen-java_gapic --java_gapic_out=metadata:dlp_java_gapic_srcjar_raw.srcjar.zip --java_gapic_opt=transport=grpc+rest,rest-numeric-enums,grpc-service-config=google/privacy/dlp/v2/dlp_grpc_service_config.json,gapic-config=google/privacy/dlp/v2/dlp_gapic.yaml,api-service-config=google/privacy/dlp/v2/dlp_v2.yaml google/privacy/dlp/v2/dlp.proto google/privacy/dlp/v2/storage.proto google/cloud/common_resources.proto
```

The protoc command in `generate_library.sh` is:
```
protoc --experimental_allow_proto3_optional --plugin=protoc-gen-java_gapic=gapic-generator-java-wrapper --java_gapic_out=metadata:java_gapic_srcjar_raw.srcjar.zip --java_gapic_opt=transport=grpc+rest,rest-numeric-enums,grpc-service-config=google/privacy/dlp/v2/dlp_grpc_service_config.json,gapic-config=google/privacy/dlp/v2/dlp_gapic.yaml,api-service-config=google/privacy/dlp/v2/dlp_v2.yaml google/privacy/dlp/v2/dlp.proto google/privacy/dlp/v2/storage.proto google/cloud/common_resources.proto google/cloud/location/locations.proto
```

Remove `google/cloud/location/locations.proto` in the protoc command can generate the right result.

**Comment by JoeWang1127** [comment]
`google/cloud/location/locations.proto` is should be added only when it's in the dependency list of a `proto_library_with_info` target.

This pattern should be searched in `BUILD.bazel`, rather than in `*.yaml`.

**Comment by blakeli0** [comment]
> `google/cloud/location/locations.proto` and `google/iam/v1/iam_policy.proto` should be added only when they are in the dependency list of a `proto_library_with_info` target.
> 
> This pattern should be searched in `BUILD.bazel`, rather than in `*.yaml`.

So the generator uses the existence of certain protos to decide if we should generate some code or not? That does not sounds like a good design decision but at least I see that it is only affecting reflec_config.json and tests.

In addition, do we know what else possible protos could be added to `proto_library_with_info`? For example, I'm curious why `google/longrunning/operations.proto` is not affected by this issue and how it is different?

**Comment by JoeWang1127** [comment]
After doing some investigation, I have the following:
1. dependencies in `proto_library` will not go to result library (`gapic-*` or `proto-*`).
2. dependencies in `proto_library_with_info` will be passed to the generator and appear in `gapic-*`
Note that if protoA imports protoB but only protoA is in the dependencies of `proto_library_with_info`, then protoA will appear in `gapic-*` but not protoB, this is the case of `google/longrunning/operations.proto`.
3. dependencies in `java_gapic_assembly_gradle_pkg` will go to `proto-*`. This is the case of [shopping](https://github.com/googleapis/googleapis/blob/master/google/shopping/merchant/inventories/v1beta/BUILD.bazel#L108-L109).
