### ISSUE TITLE
Generate proto-only libraries

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/sdk-platform-java#2047]
The `generate_library.sh` should be able to generate libraries which don't have a `java_gapic_library` bazel target.

**Comment by blakeli0** [comment]
I would call them proto-only libraries, as they are still generated through the whole GAPIC toolchain. In addition, alloydb-connector does not have a gRPC folder as well, so we should not try to run gRPC plugin as well. 
Also some other libraries like [java-iam](https://github.com/googleapis/sdk-platform-java/tree/main/java-iam) have proto and gRPC folder, but no gapic client folder. We should take those scenarios into consideration as well.

**Comment by JoeWang1127** [comment]
> I would call them proto-only libraries, as they are still generated through the whole GAPIC toolchain.

Thanks for pointing it out, I've changed the title.

> In addition, alloydb-connector does not have a gRPC folder as well, so we should not try to run gRPC plugin as well.

I noticed that even if I run the grpc plugin with the protos, there's no java file generated. I can simply delete the `grpc-*` folder if this folder is empty.

> Also some other libraries like [java-iam](https://github.com/googleapis/sdk-platform-java/tree/main/java-iam) have proto and gRPC folder, but no gapic client folder. We should take those scenarios into consideration as well.

java-iam has another issue, I need to exclude google/iam/v1/logging.
