### ISSUE TITLE
gapic-generator-java exits with `IllegalStateException` when there's no service in protos

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/sdk-platform-java#2050]
The generator should return normally with no-op when there's no service in protos.

For example: when generating from `google/cloud/alloydb/connectors/v1alpha`, the generator exited with the following error:
```
Exception in thread "main" java.lang.IllegalStateException: No services found to generate
        at com.google.common.base.Preconditions.checkState(Preconditions.java:512)
        at com.google.api.generator.gapic.protoparser.Parser.parse(Parser.java:172)
        at com.google.api.generator.gapic.Generator.generateGapic(Generator.java:30)
        at com.google.api.generator.Main.main(Main.java:28)
--java_gapic_out: protoc-gen-java_gapic: Plugin failed with status code 1.
```

**Comment by suztomo** [comment]
I would implement the script in a way that it would not call gapic-generator-java if there's no need to call it.

**Comment by JoeWang1127** [comment]
> I would implement the script in a way that it would not call gapic-generator-java if there's no need to call it.

I'm currently working on this feature. 

However, `generate_library.sh` can't decide whether to invoke generator or not. This information is stored in `BUILD.bazel`: if there's no `java_gapic_library` target, then `generate_library.sh` should not call the generator.

The grpc java plugin is implemented in a way that if there's no service to generate, it will exit normally without generating any code. I think the generator (which is also a protoc plugin) should do the same.

**Comment by blakeli0** [comment]
We discussed this in the project meeting and I agree with Joe. In addition, we have other use cases that can benefit from this change. For example, as @mpeddada1 mentioned in https://github.com/googleapis/sdk-platform-java/issues/2048, we may need the generator to generate reflect-config.json for proto-only modules.

**Comment by blakeli0** [comment]
This is working as intended, changing the type from `bug` to `feature request`.

**Comment by diegomarquezp** [comment]
cc: @lqiu96 @JoeWang1127 @alicejli 
We will address this issue by strictly causing a no-op (no output is generated) whenever no services are generated. We will leave the noop + reflect-config.json as a follow up to be addressed separately (https://github.com/googleapis/sdk-platform-java/issues/2048)

Some considerations:
 - Update documentation to explain that the generator will not fail but simply no-op
 - Add a log statement (stderr) indicating that no services will be generated
