### ISSUE TITLE
Exclude subdirectory of `proto_path` when generating from `google/api`

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/sdk-platform-java#2053]
The `generate_library.sh` should be able to exclude subdirectory of `proto_path` so that protos in subdirectory of `proto_path` will not be generated.

For example, when generating from `google/api` (part of `java-common-protos`), the generated library contains directories that should not be generated:
```
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java: grpc-google-api-java
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/java/com/google/api: apikeys
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/java/com/google/api: expr
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/java/com/google/api: servicecontrol
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/java/com/google/api: servicemanagement
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/java/com/google/api: serviceusage
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/proto/google/api: apikeys
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/proto/google/api: expr
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/proto/google/api: servicecontrol
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/proto/google/api: servicemanagement
Only in /Users/joewa/Documents/workspace/sdk-platform-java/output/google-api-java/proto-google-api-java/src/main/proto/google/api: serviceusage
```

**Comment by JoeWang1127** [comment]
For this issue, I intended to add a parameter, `include_subdirectory`, to `generate_library.sh`. This parameter is parsed from `proto_path_list.txt` and assigen a default value if not provided (that's the common case).

The default value is `false` so that only protos in `proto_path`, but not in subdirectories of `proto_path` will be generated.

I only see one library that includes subdirectories: `google/cloud/aiplatform/v1`, so to generate this library, we need to set `include_subdirectory` to `true`.

@meltsufin @blakeli0 @diegomarquezp WDYT?

**Comment by blakeli0** [comment]
Do we know why aiplatform includes the generation of subdirectory? If aiplatform is the only exception, I would prefer to just hardcode it in our script and explicitly saying that we don't support generating subdirectories, so that we don't need to add a new parameter for every edge case.

**Comment by JoeWang1127** [comment]
In aiplatform's [BUILD](https://github.com/googleapis/googleapis/blob/master/google/cloud/aiplatform/v1/BUILD.bazel), protos in subdirectories are added as dependency in `java_grpc_library` and `java_gapic_library`.

I think the service backend maybe too complex so it's helpful to split the protos into different folders.

If we don't support subdirectories, there's another way to generate this library (or libraries with similar structure): create a `proto_path` for each subdirectory and generate them into one destination folder.

**Comment by JoeWang1127** [comment]
I found another library similar to `aiplatform`: `google/cloud/gkehub/v1`.
