### ISSUE TITLE
Refactor SonarCloud showcase test coverage to show meaningful results

### ISSUE THREAD

**Issue by mpeddada1** [googleapis/sdk-platform-java#2068]
We have SonarCloud set up to track showcase coverage for both unit tests and integration tests. Integration test coverage  can help with determining how much of end-to-end behavior we are testing and also provide more relevant information as showcase ITs are handwritten. On the other hand, the unit tests are generated. 

Tracking unit test coverage can sometimes add noise to the PRs. This is particularly relevant when we are upgrading `grpc` which results in the re-generation of classes that are generated by the `gRPC proto compiler` (example: https://github.com/googleapis/sdk-platform-java/pull/1989). This makes it a little difficult to determine whether the coverage result is actionable or not. 

<img width="1108" alt="Screenshot 2023-10-04 at 5 50 28 PM" src="https://github.com/googleapis/sdk-platform-java/assets/66699525/f8724eb1-2c0e-4501-a183-04d90b44e1b5">

 Proposed changes after discussion with @burkedavison to ensure that test coverage results are more meaningful:
- Remove unit test coverage. 
- Refactor integration test coverage to only include the `gapic-showcase/` folder. This will allow us to focus on coverage for code generated by `gapic-generator-java`. 
-

**Comment by burkedavison** [comment]
@JoeWang1127 : Showcase integration test coverage currently includes class coverage in:
* `<root>/showcase/gapic-showcase`
* `<root>/showcase/grpc-gapic-showcase-v1beta1`
* `<root>/showcase/proto-gapic-showcase-v1beta1`

This should be modified to only include the classes generated by gapic-generator-java. These are found exclusively in `<root>/showcase/gapic-showcase/src/main`.
