### ISSUE TITLE
Audit usage of @BetaAPI, @InternalAPI, and @ObsoleteAPI

### ISSUE THREAD

**Issue by burkedavison** [googleapis/sdk-platform-java#2075]
Audit the usage of [@BetaApi](https://github.com/googleapis/sdk-platform-java/blob/main/api-common-java/src/main/java/com/google/api/core/BetaApi.java) in pure GAPICs to ensure current use is consistent with our intent.

**Comment by blakeli0** [comment]
Do we want to audit the usage of [@InternalAPI](https://github.com/googleapis/sdk-platform-java/blob/main/api-common-java/src/main/java/com/google/api/core/InternalApi.java) as well? I'm not sure methods marked as `@InternalAPI`  are included in the Cloud RAD or not, if they are, we may want to either remove them or add clear documentation for them. Of course, these can be different issues.

**Comment by burkedavison** [comment]
InternalAPI is not shown in Cloud RAD based on:
https://github.com/googleapis/google-cloud-java/blob/54262fd530705e063bc2a0b85f9e6c6d8e5d74e7/java-run/google-cloud-run/src/main/java/com/google/cloud/run/v2/stub/HttpJsonTasksStub.java#L209-L210
and
https://cloud.devsite.corp.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1alpha.stub.HttpJsonBatchServiceStub#com_google_cloud_batch_v1alpha_stub_HttpJsonBatchServiceStub_getMethodDescriptors__

**Comment by blakeli0** [comment]
> InternalAPI is not shown in Cloud RAD based on: https://github.com/googleapis/google-cloud-java/blob/54262fd530705e063bc2a0b85f9e6c6d8e5d74e7/java-run/google-cloud-run/src/main/java/com/google/cloud/run/v2/stub/HttpJsonTasksStub.java#L209-L210 and https://cloud.devsite.corp.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1alpha.stub.HttpJsonBatchServiceStub#com_google_cloud_batch_v1alpha_stub_HttpJsonBatchServiceStub_getMethodDescriptors__

I think it is shown in Cloud RAD based on the [link](https://cloud.devsite.corp.google.com/java/docs/reference/google-cloud-batch/latest/com.google.cloud.batch.v1alpha.stub.HttpJsonBatchServiceStub#com_google_cloud_batch_v1alpha_stub_HttpJsonBatchServiceStub_getMethodDescriptors__) you provided?

**Comment by burkedavison** [comment]
I was unclear in my "Not shown" statement. Edited above:
"InternalAPI is not displayed in the documentation of methods or classes that have been assigned InternalAPI annotations."

**Comment by blakeli0** [comment]
Thanks! I don't think we need to audit `@ObsoleteApi` as we haven't started using it yet. In addition, there is an `@InternalExtension` annotation which I don't think methods/classes marked with it should be exposed as well, so it would be great to include it as well.

For the scope of this ticket, I think we should only be looking for methods/classes that are incorrectly marked as `@BetaApi`, `@InternelApi` or `@InternalExtensionOnly`.

**Comment by burkedavison** [comment]
Audit complete. Findings split into independent tickets for implementation.
