### ISSUE TITLE
The count of outstanding RPCs in ChannelPool could go negative.

### ISSUE THREAD

**Issue by blakeli0** [googleapis/sdk-platform-java#2081]
The count of outstanding RPCs in ChannelPool could go negative in some cases, and an [exception](https://github.com/googleapis/sdk-platform-java/blob/726d02d60181dc56ffa0911757ec5516b2b5e237/gax-java/gax-grpc/src/main/java/com/google/api/gax/grpc/ChannelPool.java#L495) would be throw. In such case, there is no way a customer could recover from such error. See [internal issue](https://b.corp.google.com/issues/298510633) for details.

We need to prevent the count of outstanding RPCs to go negative and also figure out why this happened.

**Comment by meltsufin** [comment]
Do we understand how this could happen and are we able to reproduce the error?
cc: @igorbernstein2

**Comment by blakeli0** [comment]
> Do we understand how this could happen and are we able to reproduce the error? cc: @igorbernstein2

I don't think we understand how this could happen, @igorbernstein2 tried to add the [stacktrace](https://github.com/googleapis/sdk-platform-java/pull/2065) so we might be able to figure it out next time it happens. This is not reproducible either by customers, we might be able to reproduce it by digging really deep into the codebase.

**Comment by meltsufin** [comment]
In the internal bug I see some ideas. Can we try to reproduce them?
