### ISSUE TITLE
The generator should generate code and tests for Mixins if Minxins are defined in service yaml

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/sdk-platform-java#2085]
When there's Mixins in service yaml, generator should generate corresponding test code.

For example: 
In order to generate tests for the Mixins, we need to pass `google/iam/iam_policy.proto` and `google/cloud/location/locations.proto` to the generator explicitly even though Mixins defined in [baremetalsolution_v2.yaml](https://github.com/googleapis/googleapis/blob/master/google/cloud/baremetalsolution/v2/baremetalsolution_v2.yaml#L6C2-L10).

The code difference with and without Mixin protos: https://paste.googleplex.com/6122778548764672

**Comment by JoeWang1127** [comment]
Hi @blakeli0, I picked up this issue because resolving it can remove an input, `gapic_additional_protos`, of `generate_library.sh`.

IIUC, the high-level logic here is to generate Mixins (both source code and test) if they appear in service yaml (`api` section). Any other things to consider?

**Comment by JoeWang1127** [comment]
Hi @blakeli0, I found this [comment](https://github.com/googleapis/sdk-platform-java/blob/194097ad44b64a14b519cff4cc3ff615c13a7e27/gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java#L321) in Parser.

Is this (only generate Mixins APIs when Mixins are defined in service yaml as well as provided in proto list) by design?

**Comment by blakeli0** [comment]
> Hi @blakeli0, I found this [comment](https://github.com/googleapis/sdk-platform-java/blob/194097ad44b64a14b519cff4cc3ff615c13a7e27/gapic-generator-java/src/main/java/com/google/api/generator/gapic/protoparser/Parser.java#L321) in Parser.
> 
> Is this (only generate Mixins APIs when Mixins are defined in service yaml as well as provided in proto list) by design?

Good finding. I don't know if it's by design, we can ask how other languages did it. If we can simplify it to only depends on the service yaml, that would be great.

**Comment by JoeWang1127** [comment]
I spent sometime trying to solve this issue but eventually I didn't find a good solution.

I left a PR (#2194) in case anyone wants to know my intended way of solving this.

**Comment by JoeWang1127** [comment]
Judging from the answer from protobuf team, we can't get SouceCodeInfo from generated Java code (this is actual by design).

Another option we have is keeping the descriptor set files (generated when setting `--descriptor_set_out`) and generate the FileDescriptor through `FileDescriptorProto.parseFrom(InputStream input)`.

Since the descriptor set file is a binary file, we shouldn't store it in the repository. We should generate *before* running the above line of code. At this point, it's better just provide Mixins through the command line.

**Comment by blakeli0** [comment]
> Judging from the answer from protobuf team, we can't get SouceCodeInfo from generated Java code (this is actual by design).
> 
> Another option we have is keeping the descriptor set files (generated when setting `--descriptor_set_out`) and generate the FileDescriptor through `FileDescriptorProto.parseFrom(InputStream input)`.
> 
> Since the descriptor set file is a binary file, we shouldn't store it in the repository. We should generate _before_ running the above line of code. At this point, it's better just provide Mixins through the command line.

I agree with all the assessments. The benefit we got from it (not having to pass mixins protos to generate_library.sh) is not big enough to justify the behavior breaking change (no inherited comments from mixin protos). @JoeWang1127 Please document all your findings and close it.

**Comment by JoeWang1127** [comment]
Thanks, @blakeli0 , I'll commit the reason for won't fix in the internal ticket.
