### ISSUE TITLE
generator: Consider removing @BetaApi from client HTTP JSON surface

### ISSUE THREAD

**Issue by burkedavison** [googleapis/sdk-platform-java#2101]
1. Client service settings HTTP JSON builder
    * Example: https://github.com/googleapis/google-cloud-java/blob/main/java-iot/google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerSettings.java#L244-L248
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceSettingsClassComposer.java#L81

2. Client service settings builder HTTP JSON default
    * Example: https://github.com/googleapis/google-cloud-java/blob/main/java-iot/google-cloud-iot/src/main/java/com/google/cloud/iot/v1/DeviceManagerSettings.java#L287-L290
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blame/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/grpcrest/ServiceSettingsClassComposer.java#L49

3. Client HTTP JSON service stub classes
    * Example: https://github.com/googleapis/google-cloud-java/blob/main/java-iot/google-cloud-iot/src/main/java/com/google/cloud/iot/v1/stub/HttpJsonDeviceManagerStub.java#L83
    * Generation logic: https://github.com/googleapis/sdk-platform-java/blob/decd7f60017d45288e6c12493fa21e06f9c5f77c/gapic-generator-java/src/main/java/com/google/api/generator/gapic/composer/rest/HttpJsonServiceStubClassComposer.java#L217

**Comment by JoeWang1127** [comment]
Hi @burkedavison, I picked up this issue from backlog. Are the three examples the only places you want to remove the `BetaApi` annotation?

**Comment by burkedavison** [comment]
This ticket asks to "Consider" removal, so working with @blakeli0 to determine the impact of removing the annotation and making a firm decision before doing so.

The actual implementation of the removal is likely just those 3 places.
