### ISSUE TITLE
Add Structs mapper to gax

### ISSUE THREAD

**Issue by kolea2** [googleapis/sdk-platform-java#2284]
Implementation in https://github.com/googleapis/sdk-platform-java/pull/2278, we are currently adding to java-core but would want to move to gax in a utility package at some point in the future. CC @blakeli0

**Comment by blakeli0** [comment]
In addition, we might want to file a request to protobuf, as I can see this being a generic util class provided to all protobuf users. For example, I do see a [Structs](https://github.com/protocolbuffers/protobuf/blob/main/java/util/src/main/java/com/google/protobuf/util/Structs.java) class from protobuf which tries to easily construct a `Struct` type from field values, we may want to enhance it to convert from `Struct` to a `Map`.

**Comment by blakeli0** [comment]
Fixed by #2278
