### ISSUE TITLE
Release Please is not updating WORKSPACE file for _gapic_generator_java_version

### ISSUE THREAD

**Issue by suztomo** [googleapis/sdk-platform-java#2338]
Release Please does not update WORKSPACE file. A release manager needs to touch the line.

<img width="875" alt="Screenshot 2024-01-04 at 4 57 12 PM" src="https://github.com/googleapis/sdk-platform-java/assets/28604/d383243c-e68c-4c95-8cbe-7ad155aa8f96">

- Jan 4th https://github.com/googleapis/sdk-platform-java/pull/2290/commits/f6a71b73abcd80e3a7f286188d6c7fba9b411f7f (Deepankar had to manually edit the line)
- Nov 29th https://github.com/googleapis/sdk-platform-java/pull/2228/commits/6cdd786a60e95ad70a5065750da02be3327a4cc1 (Mridula had to manually edit the line)
- Oct 31st https://github.com/googleapis/sdk-platform-java/pull/2199/commits/d8d98fcadadb6667419bab81f98fa85e39027b3b (Joe had to manually edit the line)

Has it ever worked?

**Comment by mpeddada1** [comment]
It looks like this file was updated automatically by release-please for [2.28.1-SNAPHOT](https://github.com/googleapis/sdk-platform-java/pull/2186/) and [2.28.0](https://github.com/googleapis/sdk-platform-java/pull/2128/)

**Comment by suztomo** [comment]
@mpeddada1 Nice, encouraging finding. Do you want to take this issue?

**Comment by mpeddada1** [comment]
@suztomo Happy to give it a try if you're not already working on it! We're experiencing the same issue with the `.cloudbuild/` files as well.

**Comment by suztomo** [comment]
Thank you

**Comment by mpeddada1** [comment]
Looking into most recent change since 2.28.0 release: https://github.com/googleapis/sdk-platform-java/commit/96338f118f8aba7e165da7ef4b859216aa5e5aeb

**Comment by mpeddada1** [comment]
After #2349 and https://github.com/googleapis/sdk-platform-java/pull/2351/, release-please automatically updating the versions in #2350. 
Next: verify behavior for snapshot updates.

**Comment by mpeddada1** [comment]
Release-please is also working for SNAPSHOT updates now (https://github.com/googleapis/sdk-platform-java/pull/2398). Closing issue.
