### ISSUE TITLE
Encode any enums in Implicit Routing Headers as an Int

### ISSUE THREAD

**Issue by ddixit14** [googleapis/sdk-platform-java#2368]
This issue is to track encoding enums for only `implicit` routing headers.

Parent issue for both `implicit` & `explicit` routing headers - https://github.com/googleapis/sdk-platform-java/issues/1966 

For detailed info, please check out - [go/clientlibs-routine-headers-numeric-enums](http://goto.google.com/clientlibs-routine-headers-numeric-enums)

**Comment by blakeli0** [comment]
Fixed by https://github.com/googleapis/sdk-platform-java/issues/2368
