### ISSUE TITLE
Failing to Generate Code

### ISSUE THREAD

**Issue by atkawa7** [googleapis/sdk-platform-java#2416]
Good day,

Is there an example of how to use

```java
<id>gapic-generator-java</id>
                    <groupId>com.google.api</groupId>
                    <artifactId>gapic-generator-java</artifactId>
```

with a maven plugin like 

```xml
 <plugin>
          <groupId>org.xolstice.maven.plugins</groupId>
          <artifactId>protobuf-maven-plugin</artifactId>
          <version>0.6.1</version>
</plugin>
```

For now I am failing to understand what parameters are added to the 

```java
package com.google.api.generator;

import com.google.api.generator.gapic.Generator;
import com.google.protobuf.ExtensionRegistry;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorRequest;
import com.google.protobuf.compiler.PluginProtos.CodeGeneratorResponse;
import java.io.IOException;

public class Main {
  public static void main(String[] args) throws IOException {
    ExtensionRegistry registry = ExtensionRegistry.newInstance();
    ProtoRegistry.registerAllExtensions(registry);
    CodeGeneratorRequest request = CodeGeneratorRequest.parseFrom(System.in, registry);
    CodeGeneratorResponse response = Generator.generateGapic(request);
    response.writeTo(System.out);
  }
}

```

My code is only generating proto messages without stubs. I would like them to  generate `gax` classes. I am targeting `https://github.com/googleapis/googleapis/tree/master/google/apps/meet/v2beta`. Please note I am using `maven` for building.

**Comment by suztomo** [comment]
I'm afraid that the gapic-generator-java is not user GCP users but for our internal code generation pipelines. Very likely it won't work in your envrionment.

**Comment by suztomo** [comment]
Having said that, I'm curious what brought you to gapic-generator-java for your use case. Did you find a problem that gapic-generator-java could solve?

**Comment by atkawa7** [comment]
@suztomo Thanks I was able to resolve it
