### ISSUE TITLE
Make cloudbuild tests required

### ISSUE THREAD

**Issue by alicejli** [googleapis/sdk-platform-java#2479]
Currently these are 2 tests run on every PR:

graalvm-presubmit-sdk-platform-java-a (cloud-devrel-kokoro-resources)
graalvm-presubmit-sdk-platform-java-b (cloud-devrel-kokoro-resources)

They should be marked as `required` so they are forced to run on every PR.

**Comment by suztomo** [comment]
![image](https://github.com/googleapis/sdk-platform-java/assets/28604/8eed5edd-86ac-4d55-b598-0837de210338)
