### ISSUE TITLE
SonarCloud stopped working 

### ISSUE THREAD

**Issue by blakeli0** [googleapis/sdk-platform-java#2520]
SonarCloud has been reporting 0 coverage for all PRs in the past few months. It was working for a [PR](https://github.com/googleapis/sdk-platform-java/pull/2105#issuecomment-1768979134) on 10/18/2023, but not for a [PR](https://github.com/googleapis/sdk-platform-java/pull/2275#issuecomment-1846186365) on 12/7/2023. We need to investigate what changed in between.

In addition, the [total coverage](https://sonarcloud.io/project/activity?custom_metrics=coverage&graph=custom&id=googleapis_gapic-generator-java) for the repo has dropped from 90% to 20% since the mono repo migration. Which is not true, we may need to tweak some settings to make it display the correct coverage for multi-module project.

**Comment by lqiu96** [comment]
I believe this should be resolved with this: https://github.com/googleapis/sdk-platform-java/pull/1872#issuecomment-2164243448 and the java.time PR being merged in.
