### ISSUE TITLE
Add a downstream check for spring-cloud-gcp

### ISSUE THREAD

**Issue by blakeli0** [googleapis/sdk-platform-java#2534]
spring-cloud-gcp is dependent on gapic-generator-java-bom, we should make sure that any changes in this repo should not break spring-cloud-gcp by adding a downstream check. This happened in the past that a change in TestProtoLoader break SpringCodeGen, see https://github.com/GoogleCloudPlatform/spring-cloud-gcp/pull/2570.

**Comment by diegomarquezp** [comment]
@blakeli0 Do we only want to check autoconfig generation?

**Comment by diegomarquezp** [comment]
From discussion with @blakeli0, let's limit the scope to updating the generator
