### ISSUE TITLE
Log the ThreadPool size from Gax

### ISSUE THREAD

**Issue by lqiu96** [googleapis/sdk-platform-java#2680]
For the InstantiatingExecutorProvider, log the thread pool size for users to determine.

https://github.com/googleapis/sdk-platform-java/blob/5dadd4cf723e9da2e2e52d193e6b16c4b2ccb17c/gax-java/gax/src/main/java/com/google/api/gax/core/InstantiatingExecutorProvider.java#L95-L102

**Comment by blakeli0** [comment]
Do customers want to log the active thread count? or only the static max numThreads?

**Comment by lqiu96** [comment]
> Do customers want to log the active thread count? or only the static max numThreads?

The static numThreads value. Logging the active thread count would only be at a moment in time and it *should* be zero when this log is run.
