### ISSUE TITLE
Migrate Junit 4 to Junit 5: java-core

### ISSUE THREAD

**Issue by blakeli0** [googleapis/sdk-platform-java#2726]
See [this doc](https://blogs.oracle.com/javamagazine/post/migrating-from-junit-4-to-junit-5-important-differences-and-benefits) for important differences and benefits of Junit 5.
See the [official doc](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4) from Junit5 for migration tips.

In general, for each and every unit test

- If the only change is the package name, change the import statement. For example, replace `org.junit.Assert.assertEquals` with `org.junit.jupiter.api.Assertions.assertEquals`. 
- If the feature is still supported, convert the Junit 4 syntax to Junit 5 syntax. For example, replace `@Before` with `@BeforeEach`
-  If the feature is not supported anymore, re-write the unsupported part with the alternative. For example, replace `@Test(expected = …​)` with `assertThrows`.

See [example PR](https://github.com/googleapis/sdk-platform-java/pull/2724) that adds Junit 5 dependencies to gax-java and migrates one test to Junit5.

**Comment by JoeWang1127** [comment]
Some downstream libraries, e.g., java-logging, depend on a test class, [`BaseSerializationTest`](https://github.com/googleapis/sdk-platform-java/blob/2072a8c899f147b55e5f05fa6ce4296575cbb472/java-core/google-cloud-core/src/test/java/com/google/cloud/BaseSerializationTest.java#L38), in java-core.

We should wait for downstream libraries to upgrade to Junit 5 before upgrading Junit 5 in java-core.
