### ISSUE TITLE
Make library generation unit tests a required check gets stuck on child jobs

### ISSUE THREAD

**Issue by JoeWang1127** [googleapis/sdk-platform-java#2733]
The [library-generation-unit-tests](https://github.com/googleapis/sdk-platform-java/blob/main/.github/workflows/verify_library_generation.yaml#L75) sprouts two jobs: `library-generation-unit-tests (8, macos-12)` and `library-generation-unit-tests (8, ubuntu-22.04)`.

The behavior of this check when setting library-generation-unit-tests (the parent job) as required:
- On pull request that doesn't change `library_generation` directory: checks initiate and return result.
- On pull request that changes `library_generation` directory: `library-generation-unit-tests` is stuck.

The behavior of this check when setting two child jobs as required:
- On pull request that doesn't change `library_generation` directory: `library-generation-unit-tests (8, macos-12)` and `library-generation-unit-tests (8, ubuntu-22.04)` are stuck.
- On pull request that changes `library_generation` directory: checks initiate and return result.

The behavior of this check when setting parent and two child jobs as required:
- On pull request that doesn't change `library_generation` directory: `library-generation-unit-tests (8, macos-12)` and `library-generation-unit-tests (8, ubuntu-22.04)` are stuck.
- On pull request that changes `library_generation` directory:  `library-generation-unit-tests` is stuck.

**Comment by JoeWang1127** [comment]
A potential solution: remove unit tests on `macos` since it adds little value.

**Comment by suztomo** [comment]
Required checks that only run on  certain path changes are discussed in https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/collaborating-on-repositories-with-code-quality-features/troubleshooting-required-status-checks#handling-skipped-but-required-checks. I don't see we use the workaround.
