### ISSUE TITLE
Exclude google.cloud.visionai.v1.prediction.proto from scripts

### ISSUE THREAD

**Issue by alicejli** [googleapis/sdk-platform-java#2758]
https://github.com/googleapis/google-cloud-java/pull/10802 is a new library generation request for visionai.v1.
However, it failed due to prediction.proto being an empty service (e.g. no RPCs). Related issue on fixing the generator to skip generation for empty services:  https://github.com/googleapis/sdk-platform-java/issues/2750

It's excluded in the visionai.v1 BUILD file: https://github.com/googleapis/googleapis/blob/master/google/cloud/visionai/v1/BUILD.bazel#L23-L36

We need to manually exclude it here: https://github.com/googleapis/sdk-platform-java/blob/main/library_generation/generate_library.sh#L152

I'll create a separate follow-up issue on the long-term fix of either parsing BUILD.bazel to get the list of protos integrating hermetic build scripts into Bazel so that the library generation will always use the same list of protos as the BUILD.bazel file.

**Comment by alicejli** [comment]
Labeling as P1 for now as this needs to be fixed for the next release.

**Comment by alicejli** [comment]
https://github.com/googleapis/sdk-platform-java/issues/2759 is the issue for the long-term solution.

**Comment by blakeli0** [comment]
Fixed in https://github.com/googleapis/sdk-platform-java/pull/2775
