### ISSUE TITLE
api-common-java/src/test/java/com/google/api/pathtemplate/PathTemplateTest.complexResourceIdInvalidDelimiter test erroneously succeeding

### ISSUE THREAD

**Issue by alicejli** [googleapis/sdk-platform-java#2776]
https://github.com/googleapis/sdk-platform-java/blob/v2.40.0/api-common-java/src/test/java/com/google/api/pathtemplate/PathTemplateTest.java#L356

@Test
  public void complexResourceIdInvalidDelimiter() {
    thrown.expect(ValidationException.class);
    // Not a comprehensive set of invalid delimiters, please check the class's defined pattern.
    List<String> someInvalidDelimiters =
        new ArrayList<>(Arrays.asList("|", "!", "@", "a", "1", ",", "{", ")"));
    for (String invalidDelimiter : someInvalidDelimiters) {
      PathTemplate.create(
          String.format("projects/{project=*}/zones/{zone_a}%s{zone_b}", invalidDelimiter));
      thrown.expectMessage(
          String.format(
              "parse error: invalid complex resource ID delimiter character in '%s'",
              String.format("{zone_a}%s{zone_b}", invalidDelimiter)));
    }
  }

This test passes even though when the delimiter is `{`, the exception thrown actually contains the message:
`parse error: missing or 2+ consecutive delimiter characters in '{zone_a}{{zone_b}'`.

This is because of the way Junit4 handles exceptions and statefulness - it checks for an initial `thrown.expect(ValidationException.class)` and initial `thrown.expectMessage()`, which once passed, it considers it passed for the entire test.

We will need to either rewrite this test to account for "{" delimiter, or potentially refactor the way `template` works such that the exception message matches the initial test.

**Comment by blakeli0** [comment]
We should enable this test with all the passing cases. For the failing case, we should either remove it or move it to the above test that has the same error message.
