### ISSUE TITLE
api-common-java/src/test/java/com/google/api/pathtemplate/PathTemplateTest.complexResourceIdEqualsPathWildcard test erroneously succeeding

### ISSUE THREAD

**Issue by alicejli** [googleapis/sdk-platform-java#2778]
https://github.com/googleapis/sdk-platform-java/blob/v2.40.0/api-common-java/src/test/java/com/google/api/pathtemplate/PathTemplateTest.java#L310

```
@Test
  public void complexResourceIdEqualsPathWildcard() {
    thrown.expect(ValidationException.class);
    PathTemplate template = PathTemplate.create("projects/{project=*}/zones/{zone_a=**}~{zone_b}");
    thrown.expectMessage(
        String.format(
            "parse error: wildcard path not allowed in complex ID resource '%s'", "zone_a"));

    template = PathTemplate.create("projects/{project=*}/zones/{zone_a}.{zone_b=**}");
    thrown.expectMessage(
        String.format(
            "parse error: wildcard path not allowed in complex ID resource '%s'", "zone_b"));
  }
```

The first template throws the exception as expected and causes the whole test to pass. However, the second template actually does not throw any exception. Either the test needs to be rewritten or he code needs to be refactored to fix this bug.

**Comment by blakeli0** [comment]
Delete the second case should be good enough for now, since it never worked.
