### ISSUE TITLE
Unmanaged dependency check: false positive in jspecify

### ISSUE THREAD

**Issue by suztomo** [googleapis/sdk-platform-java#3063]
In https://github.com/googleapis/java-storage-nio/pull/1430, the "Unmanaged dependency check / unmanaged_dependency_check" failed:

<img width="864" alt="Screenshot 2024-07-24 at 10 17 17 AM" src="https://github.com/user-attachments/assets/6140adb9-e757-4e16-96fa-78592893f370">

The log shows:

```
Running Unmanaged Dependency Check against /home/runner/work/java-storage-nio/java-storage-nio/pom.xml
This pull request seems to add new third-party dependency, [org.jspecify:jspecify], among the artifacts listed in pom.xml.
```

I think this is false positive.

jspecify is not part of the third-party dependencies BOM: https://github.com/googleapis/sdk-platform-java/blob/802e25f8b54a4ea0308d61cc6b92e049aaed8236/java-shared-dependencies/third-party-dependencies/pom.xml#L26

**Comment by BenWhitehead** [comment]
This looks to be a transitive dependency of truth as of 1.4.4.

truth 1.4.2
```
[INFO] +- com.google.truth:truth:jar:1.4.2:test
[INFO] |  \- org.ow2.asm:asm:jar:9.6:test
```

truth 1.4.4
```
[INFO] +- com.google.truth:truth:jar:1.4.4:test
[INFO] |  +- org.jspecify:jspecify:jar:0.3.0:test
[INFO] |  \- org.ow2.asm:asm:jar:9.7:test
```

I think there are two issues at play here:
1. all `test` scoped dependencies should be ignored from the check
2. transitive dependencies should be ignored from the check

**Comment by suztomo** [comment]
I thought all tests dependencies are already ignored.

Digging further.

How to reproduce the issue locally:

```
suztomo@suztomo2:~/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check$ bom_absolute_path=/usr/local/google/home/suztomo/java-storage-nio/pom.xml
suztomo@suztomo2:~/sdk-platform-java/java-shared-dependencies/unmanaged-dependency-check$ mvn exec:java -Dexec.args="../pom.xml ${bom_absolute_path}"
[INFO] Scanning for projects...
[INFO] 
[INFO] ------------< com.google.cloud:unmanaged-dependency-check >-------------
[INFO] Building Unmanaged dependency check 0.0.1-SNAPSHOT
[INFO] --------------------------------[ jar ]---------------------------------
[INFO] 
[INFO] --- exec-maven-plugin:3.3.0:java (default-cli) @ unmanaged-dependency-check ---
[org.jspecify:jspecify]
```

**Comment by suztomo** [comment]
The workflow in the repository specifies a non-BOM for `bom-path` parameter. Maybe that's the cause.

**Comment by suztomo** [comment]
https://github.com/googleapis/java-storage-nio/pull/1430#issuecomment-2248411361 passed the unmanaged dependency check.
